add bxslider
yuu0919/freemarket_sample_43b pull request #9
Opened 2019-02-06 02:50 UTC by yuu0919

# WHAT
 画像のスライド機能を実装

## app/assets/images/index/各imageファイル
 トップページのスライド部分にあたる画像、及び矢印の画像ファイル。

## app/assets/javascripts/jquery.bxslider.js
 bxsliderを使用するためのjsファイル。
 サイトからdownloadしてjavascripts内に格納しただけで、中身は触っておりません。

## app/assets/stylesheets/application.scss
 実装したbxsliderの見た目を変えるために、application内でbxsliderのscssを読み込む記述を追加。

## app/assets/stylesheets/jquery.bxslider.scss
 bxsliderの見た目の変更により、本来の設定に変更を加えています。
### .bx-wrapper .bx-prev {}
 矢印画像の変更
### .bx-wrapper .bx-next {}
 矢印画像の変更
### .bx-wrapper .bx-controls-direction a {}
 高さ、幅の変更

## app/assets/stylesheets/modules/_index.scss
 hamlにimage_tagで書くことにより修正をしています。 
 BEMの命名に書き直しています。

## app/views/items/_bxslider.haml
 トップページのbxsliderの箇所を部分テンプレート化しています。
 こちらもBEMの命名に書き直しています

## app/views/items/index.haml
 部分テンプレート化したため、renderに変更
 最下部にbxslider.jsを読み込むためのコードを追記

## app/views/layouts/application.haml
 bxsliderを実装するのに必要な記述を追加。

## app/assets/javascripts/bxslider.js
bxsliderのオプションの記述

## config/initializers/assets.rb
bxslider.jsが読み込めるようにするためにコードを追記

# WHY
画像がスライドすることにより、動きのあるサイトになり、ユーザビリティの向上が見込めるため。

2019-02-06 10:54 UTC, yuu0919 commented
bxslider実装後のGIFです
https://gyazo.com/19df3b1778e28ba675a8581425488b45

2019-02-06 10:58 UTC, yuki-uchida requested changes

2019-02-06 10:58 UTC, yuki-uchida commented on app/views/layouts/application.haml
> +    %script
これ、他のjsファイルにかけませんか？
ここに書いてあると、後々どこにsliderのjsがあるかわからなくなってしまいます

2019-02-06 10:58 UTC, yuki-uchida commented on app/assets/stylesheets/modules/_index.scss
> +        .photo {
BEMにクラス名を設定しましょう
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-02-06 14:41 UTC, yuu0919 commented on app/views/layouts/application.haml
> +    %script
外部ファイルのbxslider.rbに書き直しました。
またhead内へのjquery の記述をやめ、index.hamlの最下部に、外部ファイルのbxslider.jsを読み込む記述を追記しました。
記述をbodyの最下部にするか迷ったのですが、indexで読み込んでいるとわかりやすくしたかったため、index.hamlの最下部にしました。

2019-02-06 14:43 UTC, yuu0919 commented on app/assets/stylesheets/modules/_index.scss
> +        .photo {
BEMに書き換えました

2019-02-07 02:11 UTC, TOMARUMARU approved these changes
LGTM

2019-02-07 02:13 UTC, merged